### ISSUE TITLE
Cannot install Modules Through Magisk Manager

### ISSUE THREAD

**Issue by JERW86** [topjohnwu/MagiskManager#178]
I'm not sure if this is a bug or this feature needs to be added again. I tried flashing a module using Magisk Manager Snapshot  v13.170531 but I either get an "installation error" message or Magisk Manager crashes.

Steps:
1. Tap modules tab
2. Tap + button
3. Choose module (tried internal and external storage)
4. Result "installation error" toast message

Attempt 2: Download from Repo

1. Tap Downloads Tab
2. Tap download button of chosen module
3. Tap install
4. Magisk Manager crash

Phone info:
Phone: XT1625 (Moto G 2016 U.S. Non-Amazon)/ROM: GZR Tesla-athene-7.1.2. OFFICIAL-20170528/Android Version: 7.1.2/Security Patch Level: May 05, 2017/Kernel: ElementalX-G4-1.08-LOS
 Magisk Manager Snapshot v13.170531
Magisk v13.170531
Thank you for your work.

Logs
[magisk_error_20170601_153036.txt](https://github.com/topjohnwu/MagiskManager/files/1045850/magisk_error_20170601_153036.txt)

[Magisk Manager Error 2.txt](https://github.com/topjohnwu/MagiskManager/files/1045863/Magisk.Manager.Error.2.txt)

**Comment by JERW86** [comment]
This behavior is still present in  Magisk Manager 5.0.0 from the official beta dated 2017.06.08

**Comment by JERW86** [comment]
Still happening with Magisk Manager 5.0.1 dated 2017.06.09
Magisk Beta v13.0.1 dated 2017.06.09.

[Magisk Manager 5.0.1 module flash Error.txt](https://github.com/topjohnwu/MagiskManager/files/1062118/Magisk.Manager.5.0.1.module.flash.Error.txt)

**Comment by dariusity** [comment]
Please let me now if my files are up to date.

1. Magisk Manager 4.3.3
2. MagiskSU r310 beta
3. Magisk v12.0

**Comment by JERW86** [comment]
This is still happening with Magisk Manager 5.0.2

**Comment by JERW86** [comment]
This has been fixed in Magisk Manager 5.0.3. Thank you. Closing.

**Comment by kkjdroid** [comment]
Still happening on Magisk Manager 5.1.1. Tried on LG G4 with Lineage 14.1 and Moto E4 with stock ROM.

**Comment by shaminz** [comment]
Happening with Magisk Manager 5.1.1 with Magisk v13.3 on Galaxy J5 Prime G570Y on Stock ROM.
When trying to install module, the error says, /data/magisk isn't installed properly. Failed. and then "Unfortunately, Magisk Manager has stopped."

**Comment by JERW86** [comment]
@kkjdroid @shaminz try clearing the manager app data. If it still continues to happen, please provide a logcat so @topjohnwu can take a look.

**Comment by JERW86** [comment]
@kkjdroid @shaminz try clearing the manager app data. If it still continues to happen, please provide a logcat so @topjohnwu can take a look.

**Comment by qimmiq** [comment]
second the problem with /data/magisk isn't installed properly.

**Comment by topjohnwu** [comment]
It's a module issue, not Magisk Manager
